### ISSUE TITLE
What feature do you wish to see in P5?

### ISSUE THREAD

**Issue by polterguy** [polterguy/phosphorusfive#12]
If you could make a wish from the top of the shelf, which feature would you want to see in the next release of P5 ...?

**Comment by iamloved** [comment]
Ah, lets see....
Yes! A graphical programming interface layer. 
Analogous to Scratch (https://scratch.mit.edu/) and Construct2 (www.scirra.com/construct2).

**Comment by eaba** [comment]
What about MS Sql Connection? I think I found only MySql!

**Comment by polterguy** [comment]
I've created feature requests for both of these issues, setting them for milestone version 4 :)
