### ISSUE TITLE
install.sh fails for me

### ISSUE THREAD

**Issue by davidbuzz** [polterguy/phosphorusfive#19]
minimal ubuntu 14.04 server install.
running install.sh as recommended in documentation.
"...
mkdir: cannot create directory '/var/www/.gnupg': file exists
 * Restarting web server apache2
  ...fail!
 * The apache2 configtest failed.
Output of config test was:
AH00526: Syntax error on line 1 of /etc/apache2/mods-enabled/mod_mono_auto.conf: 
Invalid command 'MonoAutoApplication', perhaps misspelled or defined by a module
not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
Your MySQL password can be found in the file '/var/www/html/web.config'

**Comment by polterguy** [comment]
I'm going to close this one
