### ISSUE TITLE
Shitty programming DEATH MATCH TONIGHT @ 8PM EST

### ISSUE THREAD

**Issue by polterguy** [polterguy/phosphorusfive#27]
[Read more here](https://gaiasoul.com/2018/06/22/shitty-programming-death-match-tonight/)

**Comment by eaba** [comment]
@polterguy I missed that....where is the on-demand version?

**Comment by polterguy** [comment]
Howdy Eaba, there were some few seconds from the actual match stored, but for some reasons they seem to have been taken down now ...?

I guess the administrators thought since it was mostly for fun, it wasn't worth storing. Which is a shame, since it was very funny, and highly entertaining. More than 500 people watched it, a large portion of these people watched it to the _"bitter end"_. Which was more than 3 hours in fact ...

If you wish to see what I created, you can check it out [here](https://github.com/polterguy/ingen). I have worked on it afterwards though, to create a _"use case example"_ for a Phosphorus Five app you can run locally, as an example. In general I'm quite happy with the results, and I'd say it follows most _"best practices"_ ...

It's easily installable through the "+" button in the Desktop for Phosphorus Five, and will create its own database, and everything. It features QR codes, Google Translate, Speech Synthesis, and lots of other _"goodies"_, hopefully serving as a nice use case.

[Here is a video demonstrating the system](https://www.youtube.com/watch?v=i82lruH0f8I)
