### ISSUE TITLE
Sql Server

### ISSUE THREAD

**Issue by jimmyseow** [polterguy/phosphorusfive#28]
Does this work with Microsoft Sql Server instead of mysql?

**Comment by polterguy** [comment]
Hi Jimmy, sorry it doesn't. One of my goals was to exclusively create internal dependencies upon Open Source software. But it's very easy to implement support for MS SQL server. In fact, you'd only have to look at the _"p5.mysql"_ project, and copy its logic into a new project called e.g. _"p5.mssql"_, change the database classes used, and add a reference to your Assembly into web.config ...
