### ISSUE TITLE
error: when trying to registrer user upon fresh install

### ISSUE THREAD

**Issue by iamloved** [polterguy/phosphorusfive#6]
Fresh install of phosphorus five commit: fc48313ef446a1903fa0d369578448af2b6dd64d
Using MonoDevelop 5.1 on Xubuntu 14.04
Running the debug in Chromium

So, having pulled a new phosphorus version from github through git cola. Deleted the auth file and the db folder.
Fresh install.
Opening the debug, getting asked for a salt. All fine.
Getting asked for root password. Got it and next page.
Getting asked for user name and password. Giving it, clicking on the button, error. Not allowed to next page, but instead a blank overlay 'windowbox' appear. With no message on it.

But. If I close the debug and run it again, all is fine. Everything got registered and I can login to both accounts now. 
So this is just an inconvenience that happens during the fresh install. Of course, it might confuse people.

**Comment by polterguy** [comment]
Crap, me look at it ...
BUT, when that is said, I think you only actually need to refresh the browser when you get your "blank page" ... :)

**Comment by solvenus** [comment]
Well, thats a dangerous solution, haha, because refreshing the page makes the session actually crash, and return "this webpage is not available".

**Comment by solvenus** [comment]
You fixed it, jay :D

**Comment by solvenus** [comment]
No, the error appeared again now. I have updated to latest distribution.

**Comment by polterguy** [comment]
I think this should be resolved now in the latest release, if you'd like to check it out, I'd appreciate it :)
