### ISSUE TITLE
Difficult to get started with Phosphorus 5- newbie problem

### ISSUE THREAD

**Issue by iamloved** [polterguy/phosphorusfive#7]
I want to begin using phosphorus 5 to make a social network, a place people can register and communicate with other people. Similar to how facebook is a social network, but designed completely differently.
Upon downloading the latest build from github, I began to just familiarize myself with what happens when the sys42 startup file starts.
But the sheer complexity of how the CMS (sys42) simply loads the very basic front page overwhelms me. And there are no ways to easily simplify this as of yet. It feels like trying to walk through a maze. 
I think it has to be made so that people can easily familiarize themselves with what P5 and sys42 is doing, so they can get a feel for how to code and use this. Right now it is way too raw. It is so raw how p5 is working. Like a huge, smooth wall to climb, instead of a step by step staircase to walk up.
It is hard to be a newbie in p5 currently.

**Comment by iamloved** [comment]
There has to be a course in Phosphorus 5.

**Comment by polterguy** [comment]
Hi there, and thx for the feedback. As we discussed on email, I will try to start writing an "open source book", explaining how to get started. As I do, I'd love to have both yours, and everybody else's feedback, on it ... :)

However, I will have to do this, in accordance with my time ...

**Comment by iamloved** [comment]
Sounds perfect! :+1: I can't wait ;-)

**Comment by polterguy** [comment]
Not entirely finished yet, but there's definitely a lot of info [here](https://github.com/polterguy/phosphorusfive-dox) now :)
